# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/links', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Link. As you add validations to Link, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:link)
  end

  let(:invalid_attributes) do
    { url: '' }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # LinksController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end


  describe 'GET /slug' do
    it 'renders a successful response' do
      link = create(:link, :with_slug)
      expect { get "/#{link.slug}", as: :html }.to change{ link.reload.redirects }.by(1)
      expect(response).to redirect_to(link.url)
    end

    context 'when slug not found' do
      it 'renders a not found response' do
        link = create(:link, :with_slug)
        get "/wrong", as: :html
        expect(response).to have_http_status(:not_found)
      end
    end
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Link.create! valid_attributes
      get links_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      link = Link.create! valid_attributes
      get link_url(link), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Link' do
        expect do
          post links_url,
               params: { link: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Link, :count).by(1)
      end

      it 'renders a JSON response with the new link' do
        post links_url,
             params: { link: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Link' do
        expect do
          post links_url,
               params: { link: invalid_attributes }, as: :json
        end.to change(Link, :count).by(0)
      end

      it 'renders a JSON response with errors for the new link' do
        post links_url,
             params: { link: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include('application/json')
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { url: 'https://github.com', slug: 'github' }
      end

      it 'updates the requested link' do
        link = Link.create! valid_attributes
        patch link_url(link),
              params: { link: new_attributes }, headers: valid_headers, as: :json
        link.reload
        expect(link.attributes).to include(new_attributes.stringify_keys)
      end

      it 'renders a JSON response with the link' do
        link = Link.create! valid_attributes
        patch link_url(link),
              params: { link: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the link' do
        link = Link.create! valid_attributes
        patch link_url(link),
              params: { link: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include('application/json')
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested link' do
      link = Link.create! valid_attributes
      expect do
        delete link_url(link), headers: valid_headers, as: :json
      end.to change(Link, :count).by(-1)
    end
  end
end
